-- begin CARS_CAR
alter table CARS_CAR add constraint FK_CARS_CAR_CAR_MAKE_ID foreign key (CAR_MAKE_ID) references CARS_CAR_MAKE(ID)^
alter table CARS_CAR add constraint FK_CARS_CAR_CARD_ID foreign key (CARD_ID) references WF_CARD(ID)^
create index IDX_CARS_CAR_CAR_MAKE on CARS_CAR (CAR_MAKE_ID)^
-- end CARS_CAR
-- begin CARS_CAR_PURCHASE_REQUEST
alter table CARS_CAR_PURCHASE_REQUEST add constraint FK_CARS_CAR_PURCHASE_REQUEST_CAR_ID foreign key (CAR_ID) references CARS_CAR(CARD_ID)^
alter table CARS_CAR_PURCHASE_REQUEST add constraint FK_CARS_CAR_PURCHASE_REQUEST_BUYER_ID foreign key (BUYER_ID) references DF_CONTRACTOR(CORRESPONDENT_ID)^
alter table CARS_CAR_PURCHASE_REQUEST add constraint FK_CARS_CAR_PURCHASE_REQUEST_BANK_ID foreign key (BANK_ID) references DF_BANK(ID)^
alter table CARS_CAR_PURCHASE_REQUEST add constraint FK_CARS_CAR_PURCHASE_REQUEST_CARD_ID foreign key (CARD_ID) references DF_DOC(CARD_ID)^
create index IDX_CARS_CAR_PURCHASE_REQUEST_BUYER on CARS_CAR_PURCHASE_REQUEST (BUYER_ID)^
create index IDX_CARS_CAR_PURCHASE_REQUEST_CAR on CARS_CAR_PURCHASE_REQUEST (CAR_ID)^
create index IDX_CARS_CAR_PURCHASE_REQUEST_BANK on CARS_CAR_PURCHASE_REQUEST (BANK_ID)^
-- end CARS_CAR_PURCHASE_REQUEST
