alter table CARS_CAR_PURCHASE_REQUEST add constraint FK_CARS_CAR_PURCHASE_REQUEST_BUYER_ID foreign key (BUYER_ID) references DF_CONTRACTOR(CORRESPONDENT_ID);
create index IDX_CARS_CAR_PURCHASE_REQUEST_BUYER on CARS_CAR_PURCHASE_REQUEST (BUYER_ID);
