alter table CARS_CAR_PURCHASE_REQUEST add constraint FK_CARS_CAR_PURCHASE_REQUEST_CAR_ID foreign key (CAR_ID) references CARS_CAR(CARD_ID);
create index IDX_CARS_CAR_PURCHASE_REQUEST_CAR on CARS_CAR_PURCHASE_REQUEST (CAR_ID);
