alter table CARS_CAR_PURCHASE_REQUEST add constraint FK_CARS_CAR_PURCHASE_REQUEST_BANK_ID foreign key (BANK_ID) references DF_BANK(ID);
create index IDX_CARS_CAR_PURCHASE_REQUEST_BANK on CARS_CAR_PURCHASE_REQUEST (BANK_ID);
